### ISSUE TITLE
sign up for free for open source Scout APM account

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1292] opened 2021-08-30 14:43 UTC
Switch our production app over to use that instead of heroku-plugin (which we can't get free for open source); remove heroku plugin. 

> Scout APM is free for open source! Contact us for a free account support@scoutapm.com.

https://scoutapm.com/info/pricing

Email from Scout support said:

> Thank you for reaching out! We do offer free plans for open source projects up to our large tier, however we are not able to provide this through Heroku because they have a separate billing system than us. 

> To get set up with an open source project with us you first need to switch to a direct Scout account. We are able to monitor on any environment for your monitoring needs, we would just need a github link to confirm that it was indeed an open source project. 

> To get set up with a direct Scout account here are the steps you would need to follow:
> * Visit Scoutapm.com and login to your new/personal account and input your billing information.
> * Please change your Scout key in Config Var in Heroku to SCOUT_KEY = "" (your new key will become available once your Scout account is created)
If you need to maintain the visibility into Heroku for data purposes I would suggest downgrading your account to the free plan.

**Comment by eddierubeiz** [comment] 2021-08-31 19:21
Duplicate of #1293.

**Closed by eddierubeiz** 2021-08-31 19:21 UTC
Labels: developer tools
