### ISSUE TITLE
Batch-edit of collection membership can result in heroku request timeouts (R12)

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1488] opened 2021-11-30 21:28 UTC
@apinkney0696 was using the new collection batch edit feature to move oral histories from one collection (OH) into another (Pew biomedical), and reports the problem kicks in at batch sizes between 25 and 50 works.

**Comment by jrochkind** [comment] 2021-11-30 21:31
@apinkney0696 the "batch edit" feature is the "cart" feature, first put things in cart then edit them, correct?

**Comment by jrochkind** [comment] 2021-11-30 21:38
I definitely see some n+1's in my dev console. on oral_history_content and collections too. 

50 items still only take 2-3 seconds to return in my dev instance (even when editing collection); not sure what would make it take over 30 in staging. I'm not sure there's any difference between whether you edit collections or not -- aha, maybe on staging with more collections that include more members, it may end up loading ALL members of the collections, that could make it worse on staging maybe? Not sure, it's not obvious from what I"m looking at. Would be interesting to see if it's reproducible on staging. 

either way we should fix the n+1's. Perhaps seeing if we can using new rails feature to guard against them. https://blog.saeloun.com/2020/02/25/rails-strict-loading-mode-to-fix-n-1.html

**Comment by jrochkind** [comment] 2021-11-30 21:40
I think we can turn on strict_loading with by changing `current_user.works_in_cart.find_each` to `current_user.works_in_cart.strict_loading.find_each` in Admin::WorksController#batch_update. 

Then will have to pre-load the right associations to avoid an exception. Will be interesting to see if that resolves problem... or if "the right associations" are too many associations, if we can change the logic to require loading less.

**Comment by jrochkind** [comment] 2021-11-30 21:43
Oh right, solr indexing now requires looking at all members, so it was loading all members for every work too! Another consequences of our solr indexing taking members into account! 

So that was one of the n+1s. Phew! The Rails `strict_loading` feature is super super handy here.

**Comment by jrochkind** [comment] 2021-12-01 14:12
I haven't totally been able to reproduce, but sort of. 

When I put 40 items in my cart, it batch-updated title and collection in 4 seconds. 

When I put 140 items, it took 13 seconds. 

I'm not sure if it depends on _which_ items, that is roughly proportional. None of those are long enough to cause a heroku timeout (which I think happens at 30 seconds). But they are both longer than they should be. 

Now curious to see what #1489 does to it.

**Comment by jrochkind** [comment] 2021-12-01 14:46
Hm, PR #1489 on staging did NOT seem to effect time, it still took ~14 seconds to batch edit collection+title for the 140 items in my cart. Doh! Need more investigation.

**Comment by jrochkind** [comment] 2021-12-01 20:43
Okay, so I have ~140 items in a cart, a mixture of things OH and non. 

**AFTER** fixing all the N+1 problems, when I did a batch update of just "additional title":

* it updated all the records in db in about 2-4 seconds, which is still longer than well-behaved request, but not too bad. 
* The problem was in the Solr indexing. Which is batched. 
  * It first tried sending a batch of 100 to Solr... it waited 5 seconds for a response, then timed out. 
  * Then, as traject's default logic is in response to a solr error, it tried submitting each of these 100 over again one-by-one. These all succeeded
  * Then it did the last 40 as a batch of 40, which succeeded. 
  * All this Solr indexing took another 10 seconds. 

It's possible that this is even slower for OH's, becuase OH's have all that full text we send to Solr too. Annabel's original problem case was all OH's. 

Thoughts:

* Traject when it receives a *timeout* error should maybe try the whole batch again, instead of doing one by one?
  * but maybe not, maybe it's timing out because of such a huge batch, and wouldn't with a smaller one?
* Perhaps we should reduce our solr batch size to 50, that might help. 
* SearchStax solr is annoying us by continually timing out like this... I'm realizing the huge OH fulltext's might not help
* We might just have to put the whole batch update in a BG job... figure out a way to get progress/result/error to user.  That also an include individual record validation errors though... maybe we validate first in an interactive foreground step before sending to bg for actual processing.

**Closed** 2021-12-15 16:22 UTC
