### ISSUE TITLE
Extra files found in oral history record

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#468] opened 2019-11-05 15:21 UTC
[This record](https://digital.sciencehistory.org/works/zw12z6384) appears to have additional files labeled "application/octet-stream" that do not seem to be recognized files so my guess is they should be deleted as they appear as blank boxes as seen in screenshot below: 
![image](https://user-images.githubusercontent.com/30178818/68220568-f79dfb00-ffb5-11e9-943d-dd623f3ef90e.png)

**Comment by eddierubeiz** [comment] 2019-11-05 15:24
This is a duplicate of https://github.com/sciencehistory/scihist_digicoll/issues/403 .

**Closed by eddierubeiz** 2019-11-05 15:24 UTC

**Comment by jrochkind** [comment] 2019-11-05 15:28
They should probably not be deleted, definitely not without additional investigation. 

They may be actual OH audio files taht are supposed to be on the record, but are not being processed properly.

**Comment by yonyitz** [comment] 2019-11-05 16:04
That appears to be the case as there are only 16 sound files where there should be 19.  Thanks for looking into this and let me know if I can assist further!
