### ISSUE TITLE
Indexing of multiword titles: show more results when most words match, but there are extra words in the search string.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#501] opened 2019-11-19 14:51 UTC
**Scenario:**
Search for `First Day Cover Commemorating Mr. George Washington Carver`.

**Expected results:**
The same search results (3 hits) as `First Day Cover George Washington Carver`

**Expected results (at least):**
The same search results (1 hit) as `First Day Cover Commemorating George Washington Carver`

**Actual results:**
Zero hits.

**Comment by jrochkind** [comment] 2019-11-19 14:59
Can you look at chf_sufia and see if it behaves the same as scihist_digicoll, or if this is a change?

If I understand right, you are thinking that you should get matches even if *all* your words entered don't match. What leads you to think this is the right/expected behavior?

The current behavior is intentional, here's the GH Issue from Sep 2017 where the behavior you are asking for was marked as a bug: https://github.com/sciencehistory/chf-sufia/issues/841

That issue captures some discussion in comments that led to decision. 

Doesn't mean we can't change our minds based on new situations/information/analysis/opinions. With either behavior, we will probably have some searches that aren't behaving as expected, we do want to avoid just toggling back and forth whenever we notice a situation that would  be better the other way, "grass is always greener".

**Comment by eddierubeiz** [comment] 2019-11-19 15:48
Confirmed: Sufia responds exactly the same way to the three search strings quoted above.

**Comment by jrochkind** [comment] 2019-12-02 16:39
Behavior is as intended

**Closed by jrochkind** 2019-12-02 16:39 UTC
