### ISSUE TITLE
Small SOLR bug w/ department search

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#408] opened 2019-10-07 19:48 UTC
Just logging a small bug w/ solr faceting. Start with a blank search and then open the "Department" facet.
4 items with no department show up like this:

![Department facet](https://user-images.githubusercontent.com/94723/66343519-ccbe7980-e919-11e9-8bb8-9f90f45dc101.png).

**Comment by HKativa** [comment] 2019-10-14 13:28
@eddierubeiz is there a way to see what these items without a department are? There shouldn't be any items without a department designation, unless these are test records that shouldn't be visible in any case.

**Comment by jrochkind** [comment] 2019-10-14 13:35
There's no way in the app UI, either in chf_sufia or the new app. But we can run a manual report by writing some code. I will do so shortly in both chf_sufia and new app, to see what they are and make sure they match in both. (This is easier to do in a more reliable way in the new app, but we'll want to reassure ourselves that it matches in old app, so I'll do my best to get it out of old app too).

**Comment by jrochkind** [comment] 2019-10-14 14:04
OK, in the new app production I found works with no department set like this:

    Work.where("json_attributes ->> 'department' is null OR json_attributes ->> 'department' = ''").collect(&:friendlier_id)

I actually found 7 IDs: ["pn89d691t", "dv13zv52d", "r494vk60s", "ft848q73q", "v405sb22w", "tt44pn900", "mp48sd662"]

 However, three of them are test records:   `r494vk60s`, `v405sb22w`, `mp48sd662`. (Confirmed all three are non-public test records in chf_sufia too). 

One of them is is non-public in both chf_sufia and new app production: `tt44pn900`

That leaves three that appear to be public and erroneously missing a department (not sure why this is 3 instead of the 4 suggested by the weird UI at top of this ticket; would take more investigation to figure out what's going on there):  `pn89d691t`, `dv13zv52d`, `ft848q73q`

(Note that we have a ticket suggesting feature making it impossible to mark things public without expected metadata, #372)

Now we're going to try to find all records missing department in chf_sufia, to make sure it doesn't include any additional records.  In chf_sufia, the only way to do this is via the Solr index. `http://3.93.216.251:8983/solr/collection1/select?df=*&fl=id&fq=-division_tesim:[*%20TO%20*]&fq=has_model_ssim:%22GenericWork%22&indent=on&q=*:*&wt=json`

Found 7:  "ft848q73q", "pn89d691t","r494vk60s", "mp48sd662", "dv13zv52d","tt44pn900","v405sb22w"

Matches! Same list.

**Comment by HKativa** [comment] 2019-10-14 15:28
Update: department designations added to following works: "pn89d691t", "ft848q73q", "dv13zv52d", and "tt44pn900." These works confirmed to dummy test records (no change needed):  "r494vk60s", "mp48sd662", "v405sb22w"

Re discrepancy in item count (see 3 vs. 4 items as detailed above), permissions on "tt44pn900" currently set to "your institution" since item is in queue for digitization. Not sure if this accounts for discrepancy.

**Comment by jrochkind** [comment] 2019-10-14 15:29
Doesn't account for discrepency, `tt44pn900` is correctly set to `private` on new app, and doens't show up in the facets at all. 

Discrepency may be another symptom of #374

**Comment by jrochkind** [comment] 2019-11-11 17:08
@HKativa 

I am currently finding three items in production that do not have a Department set, in case you want to update their metadata. 

http://digital.chemheritage.org/admin/works/r494vk60s
http://digital.chemheritage.org/admin/works/mp48sd662
http://digital.chemheritage.org/admin/works/v405sb22w

**Comment by jrochkind** [comment] 2019-11-11 17:10
Oh wait, my mistake @HKativa , those are all 'private'. Not currently seeing any 'public' ones! So those aren't necessarily errant. 

We still do need to change how they are indexed/displayed/saved, now that staff users can see non-public things in public UI too. 

In particular, it's a bit annoying to me that these are ending up saved with "empty string" values, instead of nil/no key.

**Comment by jrochkind** [comment] 2019-11-14 16:45
@eddierubeiz 

I think the way to fix this is in the indexer. 

If we wanted this to behave just like chf_sufia, and have things without a department be "invisible" in that facet, we'd want the indexer to make sure to _not_ index an empty string in Solr field, but when Department has an empty string instead index nothing. 

But what if we wanted it to show up as an "Unknown" or "Not Entered" facet instead? I _think_ there's a Solr feature to add a facet for "none"... that can maybe be configured, or maybe even happens automatically? So might still start with indexer not indexing empty string (rather than have indexer actually index the word "Unknown", we should lean on Solr to give us a facet for "no value").

Not sure if we want things without a Department not being listed at all in the Department facet, or being listed as a "No Value"  group. Not sure if it matters, maybe @HKativa has thoughts?

**Comment by eddierubeiz** [comment] 2019-11-14 17:08
I see what you're saying. In the interest of metadata hygiene, I would welcome a "None" facet link under e.g. department and rights, so it's easy to search for items that were mistakenly left blank. I defer to @HKativa, and would be happy to discuss this in person at the next meeting. I will say having just the count, and no way to get to the actual items, gives me a certain amount of agita.

**Comment by jrochkind** [comment] 2019-11-14 17:14
Oh yeah, it's definitely a bug now that has to be fixed. I meant to be saying: The two options are:

1. make that 'none' facet not _show up at all_. (I think that matches chf_sufia behavior)
2. make that 'none' facet actually have a label (I think I agree let's do that, if we don't hear otherwise from Hillary)
  * I think we still do this one by fixing the indexer to not index a value for empty string, but then get has-no-value to show up in facets, I forget how we do that, but I think it can be done, and some of our other facets might do it...  but I could be wrong about this.

**Comment by eddierubeiz** [comment] 2019-11-14 17:22
We're on the same page. I vote for 2. Happy to do it if we can get H. to sign on.

**Comment by jrochkind** [comment] 2019-11-19 15:26
One relevant solr setting. https://lucene.apache.org/solr/guide/6_6/faceting.html#Faceting-Thefacet.missingParameter

Can be set on a field-by-field basis. Will have to figure out how to configure it to be set in Blacklight. 

Not sure what determines what word will be used in UI for the 'missing' bucket, or if that's Solr config or just BL config.

**Comment by jrochkind** [comment] 2019-11-25 21:17
OK, this all got very confusing for some reasons we're not totally sure of!

We're going to start by making it match chf_sufia behavior -- things that don't have (eg) Department values won't show up in facets at all. (Instead of showing up with broken empty facet value you can't click on). 

Then we can consider as a separate step if we want a "no department" facet value -- one confusing thing is, if there's a "no department" facet value, should it include all Collections, since they are in search results, and none of them have department assigned?

**Comment by jrochkind** [comment] 2019-12-02 17:10
Going to use new feature in kithe that avoids sending empty strings to Solr index at all. 

Then re-index in our app staging and production. 

No further code changes in scihist_digicoll at present -- we decided chf_sufia behavior of missing values being simply missing are good enough for now.

**Comment by jrochkind** [comment] 2019-12-02 17:11
Not going to do this, going to rely on kithe feature.

**Comment by jrochkind** [comment] 2019-12-02 17:23
Fixed with kithe feature.

**Closed** 2019-12-09 16:06 UTC
