### ISSUE TITLE
Certain nonstandard mp3 files are not correctly characterized as audio

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#403] opened 2019-10-06 16:53 UTC
https://kithe.sciencehistory.org/works/zw12z6384
( post-launch: https://digital.sciencehistory.org/works/zw12z6384 )

**Comment by eddierubeiz** [comment] 2019-10-07 11:59
I'll be working on this Monday 10/7

**Comment by eddierubeiz** [comment] 2019-10-07 12:08
This may be a duplicate of https://github.com/sciencehistory/scihist_digicoll/issues/328 .

All three items are characterized as `application/octet-stream`:

https://kithe.sciencehistory.org/admin/asset_files/bc386k398
https://kithe.sciencehistory.org/admin/asset_files/k930bz06p
https://kithe.sciencehistory.org/admin/asset_files/5h73px50k

**Comment by eddierubeiz** [comment] 2019-10-07 12:47
These do appear to be mp3s of some sort. When I download the three files onto my mac, they aren't recognized by `file` as mp3s, but on the other hand `ffprobe` gives:

```[mp3 @ 0x7f986900b400] Skipping 480 bytes of junk at 0.
[mp3 @ 0x7f986900b400] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '5h73px50k.mp3':
  Duration: 00:32:09.07, start: 0.000000, bitrate: 160 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 160 kb/s```


```[mp3 @ 0x7fbb2d008200] Skipping 480 bytes of junk at 0.
[mp3 @ 0x7fbb2d008200] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'bc386k398.mp3':
  Duration: 00:02:15.10, start: 0.000000, bitrate: 160 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 160 kb/s```


```[mp3 @ 0x7f9364808200] Skipping 480 bytes of junk at 0.
[mp3 @ 0x7f9364808200] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'k930bz06p.mp3':
  Duration: 00:30:51.74, start: 0.000000, bitrate: 160 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 160 kb/s```

**Comment by jrochkind** [comment] 2019-10-07 16:00
@eddierubeiz OK, the question was why they show up in new thing prod, but not chf_sufia prod. 

But you may have found the answer -- they were the files accidentally ingested that were never meant to be ingested, they were imported to new app, they were then deleted on chf_sufia, but our deletes don't sync. 

Does that seem like what happened? If so, deleting them from scihist_digicoll seems like sufficient to close this ticket?

We do want scihist_digicoll mirroring chf_sufia, so the difference in data led to this ticket.

**Comment by eddierubeiz** [comment] 2019-10-07 16:15
No, I'm afraid that isn't the answer. If you compare https://kithe.sciencehistory.org/works/zw12z6384 with https://digital.sciencehistory.org/works/zw12z6384 and compare the titles, Kithe has "16 sound files" whereas Sufia has "19 sounds files". So these are legitimate files (when I get a chance to talk to Nicole we can talk more about exactly how legitimate) that are correctly characterized in Sufia as audio, but not in Kithe.

**Comment by eddierubeiz** [comment] 2019-10-07 16:19
Here are the asset pages in Sufia, by the way:
https://digital.sciencehistory.org/concern/parent/zw12z6384/file_sets/5h73px50k
https://digital.sciencehistory.org/concern/parent/zw12z6384/file_sets/bc386k398
https://digital.sciencehistory.org/concern/parent/zw12z6384/file_sets/k930bz06p

**Comment by jrochkind** [comment] 2019-10-07 16:21
OK, so we may have found files that _are_ intended for production, but which the pure-ruby `mimemagic` magic byte db can't identify. 

We should confirm that `file` on `jobs` machine can identify it correctly. 

If so, I think we can make the content type detection routine start by trying to use the (much faster, and more predictable) ruby mimemagic, and if it can't detect that way, resort to shell-ing out to `file`. We might make this change in the shared `kithe` code. 

Then we'll have to figure out how to rescue/restore these files in production.

**Comment by jrochkind** [comment] 2019-10-07 19:05
Took one of the files as an example, `mark_h_0030_2-5.MP3`, downloaded from sufia. 

MacOS `file` is unable to correctly identify it as audio/mpeg. 

The Harvard `fits` utility (which chf_sufia uses) _is_ able to correctly identify it. `fits` is a monster of a program, takes 5-10 seconds to run, hard to install. So we were hoping to get out of using it. 

`fits` is actually sort of an omnibus of several other embedded programs, curious to see if I can figure out which of them may be correctly identifying `mark_h_0030_2-5.MP3` as `audio/mpeg`. @eddierubeiz also noted that `ffprobe` from `ffmpeg` seems to be able to identify it (although it doesn't have a very machine-readable output; curious if `fits` is using it too).

**Comment by jrochkind** [comment] 2019-10-07 19:13
okay, the `mediainfo` utility is one of the components used by `fits`. 

It is able to identify `mark_h_0030_2-5.MP3` as `Format: MPEG Audio`.

The CLI does have easily machine readable output. 

We could install mediainfo on jobs servers (maybe avail in apt repo already; it is in macos `brew`), and drop down to mediainfo if `mimemagic` can't figure it out. 

We could also run `mediainfo` on everything, even if `mimemagic` can figure it out, to get things like duration, bit rate, etc, if we wanted to extract those. 

Currently the file identification stuff is in `kithe`, where it's not super customizable, if we were going to use something that requires an extra host OS dependency (like `mediainfo` installed), I'd want to figure out a better architecture for customizing the file identification stuff in `kithe`. See https://github.com/sciencehistory/kithe/blob/master/guides/file_handling.md#customize-the-shrine-uploader

**Comment by jrochkind** [comment] 2019-10-07 19:37
(`jhove` is also used by `fits`. At least in it's default configuration, `jhove` is _not_ capable of identifying `mark_h_0030_2-5.MP3`, it just says `MIMEtype: application/octet-stream`. https://github.com/openpreserve/jhove )

**Comment by sanfordd** [comment] 2019-10-14 19:47
I did a quick check against the copies on the Oral Histories drive and the files match their original sha512 checksum, so it doesn't look like we've got any unexpected file changes.

**Comment by eddierubeiz** [comment] 2019-11-05 15:56
Just checked with Nicole -- the three nonstandard files are indeed legitimate. We have to get them recognized as audio, one way or another.

**Comment by jrochkind** [comment] 2019-11-05 16:04
OK, we may want to prioritize this one, @HKativa ?

**Comment by jrochkind** [comment] 2019-11-05 21:29
I'm going to look into using the "mediainfo" package (that is packaged into "fits") to determine file type, as a fallback. 

@sanfordd, it looks like there's an apt repo for it -- does that mean it should be pretty easy to add to `jobs` server(s)? https://mediaarea.net/en/MediaInfo/Download/Ubuntu

**Comment by jrochkind** [comment] 2019-11-05 21:32
The three mis-characterized files in new app:

* https://digital.sciencehistory.org/admin/asset_files/5h73px50k
* https://digital.sciencehistory.org/admin/asset_files/bc386k398
* https://digital.sciencehistory.org/admin/asset_files/k930bz06p

**Comment by jrochkind** [comment] 2019-11-06 15:13
@sanfordd says we'll get mediainfo 17.12-1 on our servers, with our version of ubuntu (at least without hacking something other than the default). 

I will try to install that version on my dev server (instead of 18.08.1 I have now) to make sure it can accurately characterize those mp3s.

**Comment by eddierubeiz** [comment] 2019-11-11 20:46
This is now working in production.

**Closed** 2019-11-18 16:01 UTC
