### ISSUE TITLE
Actually add tesseract output to ones where we need to do it off-line

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2428] opened 2023-11-06 16:04 UTC

**Comment by jrochkind** [comment] 2023-11-06 16:05
See #2312 where we implemented the feature, we have to do some back-tracking to find the actual list of works!

**Comment by eddierubeiz** [comment] 2023-11-20 15:00
Duplicate of #2340

**Closed by eddierubeiz** 2023-11-20 15:00 UTC
