### ISSUE TITLE
Solutions to long audio not syncing properly in OHMS

### ISSUE THREAD

**Issue by rachellane12** [sciencehistory/scihist_digicoll#2065] opened 2023-02-13 19:27 UTC
As we discussed in our meeting on February 13, 2023, we have had issues in OHMS with long audio files not syncing properly. Doug Boyd suggested that longer files could be reduced from 96.0 kHz to 44.1 kHz sample rate and 64 kb/s to 32 kb/s bit rate. @sarahschneiderSHI is doing some testing and will report back by end of this week (February 17, 2023).

A solution @jrochkind and @eddierubeiz discussed in the meeting is generating smaller-sized audio files (copies of the originals) for the long interviews from which COH staff could sync, but not using the lower-quality audio files on the DC for the public. The thought is that the sync data should be the same since the audio file length is not changing.

**Comment by eddierubeiz** [comment] 2023-02-13 19:45
Yup! I'd be more than happy to resample some test interviews - just let me know which ones might be helpful.

**Comment by sarahschneiderSHI** [comment] 2023-02-14 14:07
Hi everyone, yesterday after our meeting, Rachel noticed that the audio from different interviews have different specifications. Some of them already have the 44.1 khz sample rate that Doug Boyd recommended. I tested out the Roald Hoffmann interview, which is over 8 hours long, but has a 44.1 khz audio sample rate and it is syncing just fine. One interview that I had trouble with (but have completed working on), Yue Xiong, has a 96 khz sample rate. Attached are screenshots from the Hoffmann and Xiong audio files, respectively, demonstrating these different rates. 
<img width="570" alt="Screen Shot 2023-02-14 at 8 58 09 AM" src="https://user-images.githubusercontent.com/103284115/218759461-dc10b5dd-be73-4c61-bd0c-048927566922.png">

<img width="510" alt="Screen Shot 2023-02-14 at 8 55 21 AM" src="https://user-images.githubusercontent.com/103284115/218758691-bd52c8ef-3729-484c-96b1-91eb0f9fe788.png">

Doug suggested the following specifications:
-Sample rate of 44.1 khz
-I believe he mentioned a bitrate of 64 kb/s, which could be dropped to 32 if needed due to a slow server

I suspect, given the Roald Hoffmann example, that the sample rate of 44.1 khz is fine for syncing. I am going to look through the NHPRC project interviews to see if there are other examples of long interviews that have a 96 khz sample rate that have trouble syncing.

**Comment by sarahschneiderSHI** [comment] 2023-02-14 14:09
Actually, it included the images in the opposite order--Xiong is first (96 khz) and Hoffmann is second (44.1 khz) in the above images.

**Comment by jrochkind** [comment] 2023-02-14 14:16
Hey @sarahschneiderSHI , I believe those are the specs on the original files you ingested into the digital collections, in the FLAC format. 

Those original FLAC ingests aren't actually the files we use with the OHMS interview editor -- the URLs you get from the Digital Collections staff interface, to use with OHMS, are actually derivatives we create, in another format. (You can't even use FLAC with OHMS editor). 

We can check to make sure those derivative files are consistently to spec, and copy here what those specs are.  But the difference in sample rate and bitrate of those original files ingested does not mean that the derivative files we use with OHMS will differ like that. 

Why those original ingested files differ is another question. I think you have a process on your end to create them from WAV?  We should review available documentation of specs and workflow, and review what was intended there, and ensure the FLACs are being created consistently to desired specs.

**Comment by sarahschneiderSHI** [comment] 2023-02-14 14:23
That makes sense--thank you for the clarification! I downloaded Xiong's interview--the combined m4a file, and the specs of the combined file are 96 khz and the Hoffmann rate for the downloaded m4a is 44.1 khz, so in those cases at least, they still stick with the theory that the 44.1 khz has less problems with syncing.

**Comment by jrochkind** [comment] 2023-02-14 14:42
If the combined derivatives differ in specs, then I think that may be a bug in our derivative creation process!  Good detective work!  Me or @eddierubeiz will take a further look. 

If the problem was just caused by us accidentally creating the derivative with too high a bitrate (eg, perhaps the same bitrate as original instead of standardizing in the derivative), we should be able to solve that fairly easily!

**Comment by eddierubeiz** [comment] 2023-02-14 15:04
So glad you found this! I'm going to be focusing on these derivatives in the next few days, so I will *absolutely* make it my business to get to the bottom of this mystery.

**Comment by sarahschneiderSHI** [comment] 2023-02-14 15:07
Thank you both! That would be great if it's a fairly easy solution.

Regarding Jonathan's previous message, I think that's a great idea to review specs and workflow for converting WAV files to FLAC files. I know that Annabel and Rachel know more about that than I do. I imagine that the original source material varies, especially since the audio files were created at different times and for different projects.

I am going to test the Yusuf Hannun interview in the OHMS backend to see if it runs into issues with syncing--I'm guessing it will since it's a fairly long interview and the combined, m4a file has a 96 khz sample rate.

**Comment by sarahschneiderSHI** [comment] 2023-02-14 17:04
Interestingly, Yusuf Hannun's interview is syncing fine. I also tried Harry Sello's interview, which is almost 11 hours long and has a 48 kHz sample rate (for the mp4 file), and that is also syncing fine. There are a couple of other long interviews for the project, but I'm not seeing any others with the 96 kHz sample rate, though there may be some in the 6 or so hour window that we can monitor. So, perhaps this isn't as big of an issue, at least in the short term for the grant project, as we thought.

I will definitely keep an eye out for any other interviews that give us trouble, and I might test one or two more later today.

**Comment by sarahschneiderSHI** [comment] 2023-02-14 19:46
Well, this is bizarre! I tried Andrew C. Chan's interview (his is 96 khz and about 6.5 hours) and his interview is syncing fine. I then created a test record for Yue Xiong (which I had a lot of trouble with previously) and it worked fine. I then went back to the original Xiong OHMS entry and it seems to be working fine there also.

I have no idea why this would be, but I wonder if something changed between when I was working on the difficult interview a few weeks ago and now? Previously, it would be delayed/move slowly and often skip over the chiming noise at the minute mark, making it difficult to tag the right spot in the interview.

**Comment by jrochkind** [comment] 2023-02-14 19:49
We deliver the audio directly from S3, which isn't optimized for reliable content delivery. It's possible that some days it's delivering the bytes slower to your browser than others, and this is affecting things. But this is just a guess, and not a super confident one. 

We have an existing backlog issue to look into optimizing delivery of our assets. https://github.com/sciencehistory/scihist_digicoll/issues/705

I'm glad you are doing okay going forward, but we should still at a minimum go over things on our side to make sure we understand what the desired specs for the m4a derivative are (with regard to bitrate etc), and that we are producing them consistently. We shouldn't be producing m4a combined audio derivatives with different bitrates from each other. 

(Also I think they should all be constant-bit-rate (CBR) rather than variable bit rate (VBR), because CBR is necessary for reliable browser seeking forward/back).

**Comment by sarahschneiderSHI** [comment] 2023-02-14 19:56
That could explain it!

That is all good to know and sounds good, thanks.

I also forgot to mention earlier that Doug Boyd suggested that saving things as a mono file (which some files already are) rather than a stereo file might help with file sizes.

I will keep an eye out for any future issues, and hopefully @rachellane12 can as well.

**Comment by jrochkind** [comment] 2023-02-14 19:58
Thanks for mentioning mono/stereo! When/if y'all go over your procedures for _creating_ those FLAC files, I'd encourage you to consider creating them as mono files -- since our original recordings aren't in stereo anyway.  

That would make it easier for us to know when we can create derivative audio files that are also mono -- as in some cases (in the future if not present) the digital collections may include stereo audio files, and we don't want to go just downsampling them all to mono, the software would have no good way to tell when a stereo audio file was unnecessarily stereo.

**Comment by rachellane12** [comment] 2023-02-15 12:33
@jrochkind I agree that we should definitely address the procedures for creating FLAC files/how to handle legacy files because I think ideally they should be consistent bit rate/sample rate except if there is a clear reason in the workflow to deviate. We have a team meeting today for the Center for Oral History so I'm planning to bring this up then.

**Comment by apinkney0696** [comment] 2023-03-20 16:42
Fwiw, the workflow for creating .flac files is located here: https://files.sciencehistory.org/navigate/file/ce582091-231d-4c5e-be94-0a2f3c59c58e

**Comment by apinkney0696** [comment] 2023-03-20 16:59
Closing as Eddie wrote up specs for audio files ( #2082) in the wiki.

**Closed by apinkney0696** 2023-03-20 16:59 UTC
