### ISSUE TITLE
On the admin works page, allow user to check and uncheck all works on the page at once.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2657] opened 2024-06-17 18:56 UTC
On the admin works page, allow user to check and uncheck all works on the page at once.
(This adds (or removes) said works to the cart.)

This should result in one DB call per click, regardless of the number of works checked or unchecked.

**Comment by jrochkind** [comment] 2024-08-08 17:42
Duplicate of #2615

**Closed by jrochkind** 2024-08-08 17:42 UTC
