### ISSUE TITLE
Discrepancy in mp3 file length when played in an <audio> or <video> tag in Chrome

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1646] opened 2022-04-08 19:44 UTC
1) Download the 7 segments that make up the [Djerassi interview](https://digital.sciencehistory.org/works/hm50ts561#tab=ohDownloads)
and figure out their length using, e.g.,  `ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 filename.mp3` .

2) Sum the lengths:
`1724.232 + 1625.520 + 1798.776 + 925.104 + 1842.792 +  1751.640 + 1672.560 = 11340.624`
`11340.624` is `3:09:00.624`

3) Using Chrome, go directly to the [public version of the combined audio derivative as served from s3](https://scihist-digicoll-production-derivatives.s3.amazonaws.com/combined_audio_derivatives/e79319b9-0df3-4cc3-9929-b4c81bfd1e4b/combined_64acb3ab42b75b9dc8caee2563994843.mp3).

![so far so good](https://user-images.githubusercontent.com/94723/162516674-83adfb00-fa4b-439e-b8d0-12bc81b8cf5c.png)

4) Drag the playhead to the end of the scrubber.

5) Click the play button.

6) The audio continues to play, updating BOTH the current position of the audio AND the total length of the audio, until over a minute later both numbers come to rest at 3:10:04.

7) Visit the [Djerassi interview in the digital collections](https://digital.sciencehistory.org/works/hm50ts561), again in Chrome. You can easily reproduce the same behavior by repeating steps 4 and 5.

Thanks to @sarahschneiderSHI for helping describe this.

**Comment by sarahschneiderSHI** [comment] 2022-04-08 20:12
[](url

https://user-images.githubusercontent.com/103284115/162519081-bcc919bf-2f3c-4096-9690-3ad677aa9094.mov

) In this video, you can see that the time of the interview is increasing in both the full interview time and the time of the current spot in the interview (both numbers on the media player are simultaneously increasing). This sometimes (but not always) occurs after clicking on "Play Segment" in the final Table of Contents entry (That starts with "Transparency and ethics...").

**Comment by sarahschneiderSHI** [comment] 2022-04-08 20:18
This may be a few seconds off, but the totals of each interview audio file I have are:
28:47
27:08
30:00
15:27
30:45
29:11
27:54
**This results in the total of: 3:09:12**

**Comment by jrochkind** [comment] 2022-04-08 20:55
I'm still confused about what you're reporting as a problem @eddierubeiz. Can you report it being clear about what you expect to see, and how that differs from what you do see? 

If this is something someone else pointed out to you that you are just filing the issue on, we could ask them to do that, to make sure we have it right. 

If part of the issue is that the timecode Chrome is reporting as the length is shorter than what Chrome will actually play (that seems to suggest ffmpeg is creating some odd mp3's as output of the concatenate): It would also be interesting to look at the file in a desktop player, compared to Chrome. As well as in other browsers -- and what  ffprobe and mediainfo report as the length. 

Before investing *too* much time in this we should also decide how much of a priority it is, actually prioritize it at a Monday meeting. 

Also, re-create the combined derivative just to be sure it's using the up to date code for doing so.

**Comment by eddierubeiz** [comment] 2022-04-08 21:13
I don't believe the file is any longer than 3:09:00; if you download the combined audio derivative, ffprobe will tell you it's about 11340 seconds long.

My expectation is that when I scrub the playhead to the end of the file in our audio player in Chrome, I should not be able to hit the play button and hear an extra minute of audio, with the reported file length in Chrome's audio player ending up at 3:10:04.

I have reservations about re-creating the combined audio derivative automatically in the browser. I don't want to mess with the crime scene, as it were. The offsets in the transcript refer to this particular file.

I have to wrap up for the day, unfortunately, but we can discuss more on Monday, and of course test in a bunch of other players.

**Comment by eddierubeiz** [comment] 2022-04-13 21:10
Due to a bug in Chrome, it's possible to confuse audio players such that the offset of the current location within an mp3 file and/or the length of the file are incorrect.

The problem only happens when playing mp3s in Chrome, and can be tricky to reproduce. That said, it does affect audio and video players both inside and outside of the digital collections. Nobably, I've reproduced it in a) the stock player in s3, and also b) the jPlayer widget used in https://ohms.uky.edu/sync.php.

The fact that the problem (again, only in Chrome) affects https://ohms.uky.edu/sync.php explains how it was possible for us to record TOC timecodes that are AFTER the end of the audio for the Djerassi combined audio derivative.

Note that once the bug has occurred within a given player, other time offsets reported in that same player can also be incorrect, even after moving the playhead back and forth within the file. I believe this may have caused a series of incorrect timecodes in our OHMS tagging of the Djerassi interview.

Note, however, that the internal duration metadata in our combined audio derivatives is correct: for instance, the length of the audio for the complete Djerassi interview (regardless of format) is exactly 03:09:00 in duration.

**Comment by jrochkind** [comment] 2022-04-13 22:29
How did you determine that the internal duration metadata is correct?

Is it on the basis of that determination that you conclude it's a bug in Chrome? Can you find the bug reported as a bug in Chrome anywhere? 

Can you reproduce it with any mp3's that weren't created by us? 

I feel like we should at least definitely consult with the OHMS list on this. 

I wonder if we can give a different format to OHMS to get the correct timecode. We're already creating webm... I don't know if that will work with OHMS or not (does anything that the browser can play work?); but I think I saw some OHMS documentation suggesting .mp4 audio; perhaps we could switch to mp3 and AAC-in-mp4; or even just mp4 if all browsers support it -- I'm having trouble figuring out what browsers support it.

**Comment by eddierubeiz** [comment] 2022-04-14 15:09
My short-term aim was to provide a workaround for Sarah, who does have access to Safari, so most of the initial work I did was comparing Chrome to Safari and ascertaining that it was impossible to reproduce the problem in Safari. Yesterday Sarah was able to recode the Djerassi interview using Safari, and the time codes are now correct by her assessment. So the immediate crisis is behind us.

Now going back to the wider problem: there are lots of claims of bugs in mp3 length with Chrome, but most focus on problems with more complex sound files with variable bit rates and/or several tracks or segments. By comparison, our combined file is really simple.

We resample the audio as we combine it, and write everything out to a single mono track at a fixed rate of 64 kb/s.

On s3, the combined file is 725788008 bits in size.
725788008 bits / 64000 bits per second = 11340.437625 seconds.
The internal metadata 11340.41 seconds.
The 27ms extra in the quotient is accounted for by the bytes taken up by metadata at the beginning of the file.

I'm puzzled that I haven't been able to see more reports about this problem, but I can spend some more time researching it. It's entirely possible you could reproduce it in Edge or Firefox, which would be really interesting and definitely undermine my claim that it's strictly a Chrome problem. Avenues for further research.

**Comment by eddierubeiz** [comment] 2022-04-14 15:13
Oh, and I created a bogus interview in Ohms and tried assigning it a combined derivative that wasn't an mp3. I couldn't get flac, ogg, or webm to work, which is disappointing considering the [jplayer docs](https://jplayer.org/latest/developer-guide/).

**Comment by eddierubeiz** [comment] 2022-04-14 15:15
I didn't try reproducing it with other mp3, no, but that's definitely one of the things we could do now.

**Comment by jrochkind** [comment] 2022-04-25 15:50
See #1654 where we are moving forward with moving to m4a format instead.

**Closed** 2022-04-25 15:50 UTC
