### ISSUE TITLE
OHMS Front End: TOC Segment Scrolling

### ISSUE THREAD

**Issue by lsberry16** [sciencehistory/scihist_digicoll#689] opened 2020-04-03 16:20 UTC
If you expand a TOC segment and then expand the next segment without collapsing the previous one, the display scrolls all the way to the bottom of the newly-expanded segment (bad), I guess because it's auto-collapsing the previous one (good). I noticed this specifically in the Renfrew TOC:
https://staging-digital.sciencehistory.org/works/1n79h560c#ohToc

but I don't know that it's limited to that.

**Comment by jrochkind** [comment] 2020-04-06 14:05
I'm having trouble reproducing this. There is a little bit of "jumping around" that happens, but when it all settles down, for me, the section that you just expanded is properly alligned with the top of it right below the navbar. 

The "jumping around" is unfortunate, but I couldn't figure out how to fix it, using the accordion tools we are using. I also think the weird "jumping around" happens too, at least to some extent, in the standard OHMS viewer and the Brooklyn Historical Society too.

**Comment by eddierubeiz** [comment] 2020-04-06 14:08
I interpreted this as just "WHEN you change which accordion flap is shown, IF the newly visible flap is taller than the screen, THEN please show the top of that flap, INSTEAD OF the bottom."

**Comment by jrochkind** [comment] 2020-04-06 14:10
@eddierubeiz Thanks, that helps.  Now that you put it like that, I can reproduce! Sorry, I missed the part about the newly visible section being taller than the screen, good catch. 

Which surprises me, I thought this would already do the right thing. Hmm. I can hopefully fix it.

**Comment by jrochkind** [comment] 2020-04-06 15:57
Aha, I think I actually already have this fixed in the "search" branch that isn't deployed yet. Was part of my confusion!

I should have fixed it in a separate branch that could have been merged/deployed independently -- will work on extracting it out into it's own thing, so we can get it merged, since it was identified by @lsberry16  as high priority.

**Closed** 2020-04-20 15:06 UTC
Labels: OHMS
